
// Segunda 1
//  terça-feira 2
// quarta-feira 3
// quinta-feira 4
// sexta-feira  5
// sábado 6
// domingo 7
let semanas = Number(prompt(`qual dia da semana`))
switch (semanas) {
            case 1 :
            console.log(`segunda-feira`);
         break;
            case 2 :
            console.log(`terça-feira`);
            case 3 :
            console.log(`quarta-feira`);
             break;
            case 4 :
             console.log(`quinta-feira`)
             break;
             case 5 :
             console.log(`sexta-feira`)
             break;
            case 6 :
          console.log(`sábado`)
             break ;
             case 7 :
                console.log(`domingo`)



          break;
    case value:
        
        break;

    default:
console.log(`dia não encontrado`)
        break;
}